
package com.sondertara.common.bean.copier;

/**
 * A copier generated by the BeanCopy analyzer.
 * 
 * @author huangxiaohu
 */
public interface Copier {
  /**
   * copy
   * 
   * @param source source object
   * @param target target object
   */
  void copy(Object source, Object target);
}
